arb-dir: lib/assets/locales
template-arb-file: en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/common/libraries/localizations
nullable-getter: false
