name: streetballer
description: Find courts, organise pick-up games, and compete with others.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.8.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  mapbox_maps_flutter: ^2.5.0
  google_maps_flutter: ^2.17.0
  geolocator: ^14.0.0
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  envied: ^0.5.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^0.5.4
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true

  # assets and fonts will be added as files are introduced
  assets:
    - lib/assets/icons/
    - lib/assets/images/
  fonts:
    - family: DM Sans
      fonts:
        - asset: lib/assets/fonts/dm_sans-400.ttf
          weight: 400
        - asset: lib/assets/fonts/dm_sans-700.ttf
          weight: 700
